source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "webrick"
gem "csv"
gem "jekyll-avatar"
gem "jekyll-feed"
gem "jekyll-mentions"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-redirect-from"